xmtp/xmtp-flutter

lib/src/api.dart, lib/src/auth.dart, lib/src/contact.dart, lib/src/content.dart, lib/src/crypto.dart, lib/src/topic.dart, pubspec.yaml, test/contact_test.dart, test/crypto_test.dart, test/integration_test.dart
This includes the low-level bits required for V1 messaging.
It includes
- a refactor of how the auth uses private key bundles to more closely track the JS lib (i.e. storing/loading V1 bundles)
- adapters for converting between v1 `PublicKeys` and v2 `SignedPublicKeys`
- an implementation of our variation on X3DH for message encryption keys
=> feat: low-level support for v1 messaging

.github/workflows/test.yml, test/auth_test.dart, test/client_test.dart, test/contact_test.dart, test/conversation/conversation_v1_test.dart, test/conversation/conversation_v2_test.dart, test/test_server.dart
This spins up a local node during test runs and enables the tests that depend on it.
=> build: add test network to CI and enable more tests

CHANGELOG.md, pubspec.yaml
This bumps the version so we can `dart pub publish` to pick up the latest docs.
=> build: bump preview release version to development.1

lib/src/common/api.dart
Fixes https://github.com/xmtp/xmtp-flutter/issues/23
When trying to setup the example app locally. I ran into an issue with local versus dev. 
I think it will be easiest for others spinning up this environment to default to dev instead of local.
=> feat: default to dev network instead of local

test/client_test.dart
This fixes some integration tests that relied on ~immediate message propagation.
e.g. [this test run](https://github.com/xmtp/xmtp-flutter/actions/runs/3833243073/jobs/6524486734) (failing because the test tried to use a just-created account before the published contact message had propagated).
=> test: add delays to allow message propagation in integration tests

lib/src/client.dart, lib/src/contact.dart, test/client_test.dart
This makes it easier to check if an address can receive a message.
=> feat: add canMessage(address) to Client

lib/src/auth.dart, lib/src/contact.dart, test/client_test.dart, test/contact_test.dart
We had reports of missing messages from `xmtp-flutter` apps in the example react app and other web clients that use `xmtp-js`. See #28. (See also https://github.com/xmtp/xmtp-ios/issues/28 which might be related)
This seems to fix that issue. The underlying cause was that the `xmtp-js` library only accepts `identityKey` signatures of type `.walletEcdsaCompact` but the `xmtp-flutter` library was signing the `identityKey` signature as type `.ecdasCompact`.
This PR converts the signature to the expected type when we assemble contact bundles.
Note: this PR doesn't change the `.identityKey` logic for creating auth tokens. This is because the backend has ([used to have](https://github.com/xmtp/xmtp-node-go/pull/193)) the opposite expectation for `.identityKey` signatures on auth tokens. Once …
=> fix: sign v2 id key using .walletEcdsaCompact instead of .ecdsaCompact

lib/src/conversation/conversation_v2.dart, test/client_test.dart, test/conversation/conversation_v2_test.dart, test/test_server.dart
This fixes #35 and unifies treatment for invalid envelopes with `xmtp-js`.
The envelope and the invite must have the same timestamp. 
Outgoing: Previously `xmtp-flutter` was constructing invites such that they could differ a bit (it was calling `nowNs()` twice). Now, with this PR, the timestamps are constructed to match.
Incoming: Previously `xmtp-flutter` didn't care if it received an invite with mismatching envelope/invite timestamps. This caused conversations to appear that were discarded by other clients. Now, with this PR, invites with mismatching timestamps are discarded (consistent with `xmtp-js`).
=> fix: pin timestamp on invite to envelope, drop invalid

lib/src/auth.dart, test/client_test.dart
The prior merge failed to sync the latest test helper name change. This fixes that and removes some log messages that made test runs harder to read.
=> fix: fix the bad merge, trim spurious debug messages

lib/src/common/signature.dart, test/common/signature_test.dart
Together with #29 I think this should close #21
=> fix: converting to address when public key has leading zero-bytes

README.md, example/README.md
- Based on dev feedback, added a clarification that interoperable inboxes are the default state
- Also pulled the example app note into this PR. Thought it would be helpful to provide the note now. Don't need to wait for GA. =)
=> Clarify that interoperable inbox is the default, add example app note

lib/src/common/signature.dart, lib/src/conversation/conversation_v2.dart, test/conversation/conversation_v2_test.dart
This prevents someone from sending a message with a pre key that wasn't properly signed by the identity key.
=> fix: discard messages with invalid sender key bundles

lib/src/client.dart, lib/src/common/api.dart, lib/src/conversation/conversation_v1.dart, lib/src/conversation/conversation_v2.dart, lib/src/conversation/manager.dart, lib/xmtp.dart, test/client_test.dart, test/conversation/conversation_v1_test.dart, test/conversation/conversation_v2_test.dart, tool/local-node/docker-compose.yml
This adds 3 new methods to the SDK for help with performance tuning:
- `listBatchMessages` -- lists messages from multiple conversations in a single call
- `streamBatchMessages` -- streams new messages from multiple conversations in a single call
- `sendMessageEncoded` -- sends a message that was already previously encoded
=> feat: add batch editions of list/stream messages and send encoded

lib/src/common/api.dart
Be nice to bump the version for the security release.
Wondering if we can automate this like we do on android: https://github.com/xmtp/xmtp-android/blob/main/.github/workflows/release.yml#L22-L33
But at the very least we can bump this to `0.0.2-development.1`
=> Bump version

lib/src/conversation/conversation.dart, lib/src/conversation/conversation_v1.dart, lib/src/conversation/conversation_v2.dart, lib/xmtp.dart, pubspec.yaml, test/conversation/conversation_v1_test.dart, test/conversation/conversation_v2_test.dart
This PR implements a single content topic per query request to make it easier to fetch queries in a future decentralized node world. It replaces the two instances of `QueryRequest` that took in multiple content topics with the new `BatchQueryRequest` which allows us to keep the current SDK structure while enforcing this new rule.
Related Android PR: https://github.com/xmtp/xmtp-android/pull/52
Related iOS PR: https://github.com/xmtp/xmtp-ios/pull/81
=> refactor: use BatchQuery to list messages for multiple conversations

.github/workflows/release.yml, CHANGELOG.md
This PR fixes a small auth issue with our publishing flow via `release.yml`. This should fix the publishing step getting stuck on auth like it did for the `v0.0.3` build: https://github.com/xmtp/xmtp-flutter/actions/runs/4608928269/jobs/8145355539#step:11:104.
I bumped the version number to `v0.0.4` in the CHANGELOG to try again.
=> fix: use JWT token when publishing dart package

CHANGELOG.md, README.md, lib/src/common/api.dart, lib/src/contact.dart, test/contact_test.dart
Relates to https://github.com/xmtp/xmtp-js/issues/371.
We were noticing some malformed v1 contact bundles causing invalid signatures on the network. It appears the root cause might be this SDK publishing a `walletEcdsaCompact` signature for v1 contact bundles instead of a `ecdsaCompact` signature.
This PR updates the v1 contact bundle to publish a `ecdsaCompact` signature. I tested creating a new identity `0xE7CAa710E60A2Ae19EdfCbF1be7aD500F4656c81` locally in the example app and confirmed I can message with xmtp.chat and the iOS app.
**Note:** This also fixes the SDK version reported to the network and adds a step to update it in the publishing docs in the README. This release will be `v1.0.0` since we are officially GA'd.
=> fix: use `ecdsaCompact` signature for v1 contact bundle

lib/src/common/crypto.dart, lib/src/conversation/conversation_v2.dart, test/conversation/conversation_v2_test.dart
This produces consistent `topic` and `keyMaterial` for invites created to the same `peer` and `conversationId`.
This implements #62
=> feat: use deterministic topic/keyMaterial invite generation

lib/src/common/api.dart, lib/src/conversation/conversation_v1.dart, lib/src/conversation/conversation_v2.dart, test/client_test.dart
This modifies the `listConversations` call to properly gather all conversations across the paginated results.
Fixes https://github.com/xmtp/xmtp-flutter/issues/70
=> fix: list all conversations across multiple query pages

lib/src/client.dart, lib/src/common/api.dart, lib/src/conversation/conversation_v1.dart, lib/src/conversation/conversation_v2.dart, lib/src/conversation/manager.dart, test/client_test.dart, test/conversation/conversation_v2_test.dart
This modifies the `listMessages` / `listBatchMessages` calls to properly gather all results across multiple pages. This uses batch queries to get the initial page and any subsequent pages.
Fixes #71
=> fix: batch paginate across multiple queries

CHANGELOG.md, lib/src/common/api.dart, lib/src/conversation/conversation_v2.dart, test/conversation/conversation_v2_test.dart
Part of https://github.com/xmtp/xmtp-js/pull/449
Lets make topics deterministic in either invite direction
=> fix: update the invitation to create topics without direction

CHANGELOG.md, lib/src/common/api.dart, test/client_test.dart
fixes https://github.com/xmtp/xmtp-flutter/issues/89
Respects limit when batching messages
=> fix: Respect limits on batched messages

.gitignore, example/.metadata
- Removing the references to the platforms that are not supported in this SDK according to the comments made by @dmccartney in PR -> https://github.com/xmtp/xmtp-flutter/pull/101/files
=> Removing unnecessary platforms

lib/src/content/codec_registry.dart, test/content/codec_registry_test.dart
This adds support for compression (compress/decompress) to the codec registry for all content.
This is the first piece of a refactored approach to remote attachments (picking up https://github.com/xmtp/xmtp-flutter/pull/105)
=> feat: support compression on encoded content types

lib/src/client.dart, lib/src/content/remote_attachment_codec.dart, test/client_test.dart
This adds support for remote attachments.
=> feat: support remote attachments
