xmtp/xmtp-flutter

- lib/src/content.dart
- lib/src/crypto.dart
- test/integration_test.dart
This includes the low-level bits required for V2 messaging.
> feat: low-level support for v2 messaging

- lib/src/auth.dart
- lib/src/client.dart
- lib/src/common/crypto.dart
- lib/src/common/signature.dart
- lib/src/contact.dart
- lib/src/content/decoded.dart
- lib/src/conversation/conversation.dart
- lib/src/conversation/conversation_v1.dart
- lib/src/conversation/conversation_v2.dart
- lib/src/conversation/manager.dart
- lib/xmtp.dart
- test/auth_test.dart
- test/client_test.dart
- test/common/crypto_test.dart
- test/contact_test.dart
- test/conversation/conversation_v1_test.dart
- test/conversation/conversation_v2_test.dart
This restructures the object model to be more offline-storage friendly.
Also included:
- fixed a bug with preKey signing
- simplified the interface to `conversationId`/`metadata`
> feat: refactor object models to simplify offline storage

- example/lib/database/adapters.dart
- example/lib/database/database.dart
- lib/src/client.dart
- lib/src/content/codec_registry.dart
- lib/src/content/composite_codec.dart
- lib/src/content/decoded.dart
- lib/src/conversation/conversation_v1.dart
- lib/src/conversation/conversation_v2.dart
- lib/xmtp.dart
- test/client_test.dart
- test/content/codec_registry_test.dart
- test/content/composite_codec_test.dart
This adds support for custom content-type `Codecs`. It also includes support for the `Composite` content type.
> feat: custom codec support, composite type support

- .github/workflows/release.yml
- CHANGELOG.md
- pubspec.yaml
This adds a workflow to publish builds to pub.dev.
> build: add release workflow

- CONTRIBUTING.md
- README.md
- Adds all XMTP-generic content to README
- Provides placeholders for Dart-specific content
- Please search on "dan" to find these placeholders. =)
- And of course, you don't need to provide content for all placeholders - just ones that you are ready to provide and that you think will be useful for the Dev Preview. We can always iterate!
> First pass on README updates, adds CONTRIBUTING file

- example/lib/main.dart
- example/lib/pages/home_page.dart
- example/lib/pages/login_page.dart
- example/lib/router.dart
- example/lib/session.dart
- example/lib/wallet.dart
- example/pubspec.yaml
- lib/src/auth.dart
- lib/src/client.dart
- lib/src/common/api.dart
- lib/src/common/signature.dart
- lib/xmtp.dart
- test/auth_test.dart
- test/client_test.dart
- test/contact_test.dart
- test/conversation/conversation_v1_test.dart
- test/conversation/conversation_v2_test.dart
This demonstrates the WalletConnect login flow in the example app.
It also simplifies the wallet creation interface.
> feat: example walletconnect login flow

- example/lib/components/address_chip.dart
- example/lib/config.dart
- example/lib/ens.dart
- example/lib/hooks.dart
- example/pubspec.yaml
- example/test/ens_test.dart
This adds basic ENS name resolution to the example app.
> feat: include basic ens resolution in the example app

- lib/src/client.dart
- lib/src/conversation/conversation_v1.dart
- lib/src/conversation/conversation_v2.dart
- lib/src/conversation/manager.dart
- test/client_test.dart
This clarifies the error returned for #31
> fix: disable self-messaging

- tool/local-node/docker-compose.yml
This mirrors the fix from https://github.com/xmtp/xmtp-js/pull/262 (see for more context).
> build: tweak node-go config for latest image

- lib/src/conversation/conversation_v2.dart
- test/conversation/conversation_v2_test.dart
> fix: verify payload signature on v2 messages

- lib/src/auth.dart
- lib/src/common/crypto.dart
- lib/src/common/signature.dart
- lib/src/conversation/conversation_v1.dart
- lib/src/conversation/conversation_v2.dart
- test/auth_test.dart
This is a non-functional change to use a sync edition of sha256.
> feat: use sync sha256

- .github/workflows/release.yml
- .github/workflows/test.yml
- example/pubspec.yaml
- pubspec.yaml
This bumps dependencies across the board.
I carved this out as a standalone PR from the ongoing work in #56
> build: bump dependencies

- lib/src/auth.dart
- lib/src/common/signature.dart
- test/auth_test.dart
- test/client_test.dart
- test/contact_test.dart
- test/conversation/conversation_v1_test.dart
- test/conversation/conversation_v2_test.dart
This tidies up some analysis nits brought on by #58
> fix: remove analysis nits, drop unnecessary awaits

- lib/src/client.dart
- lib/src/conversation/conversation_v1.dart
- lib/src/conversation/conversation_v2.dart
- lib/src/conversation/manager.dart
- test/client_test.dart
This adds support for out-of-band decryption of pushed conversations and messages.
> feat: support out-of-band decryption of conversation/message envelopes

- lib/src/conversation/conversation_v2.dart
- test/conversation/conversation_v2_test.dart
This tests that identical keys produce matching invitations between the JS and flutter SDKs.
> fix: join with comma to fix deterministic invites

- README.md
- Update "General Availability" status to "Production" status according to revised status names
- Remove content about conversation IDs
- Update links
> Docs: A few README updates

- example/lib/session/background_manager.dart
Just a small error that was stopping the example app from building.
> fix: example app error

- lib/src/content/read_receipt_codec.dart
- test/content/read_receipt_codec_test.dart
- Adding the codec similiar of how it works in Android and iOS, [example](https://github.com/xmtp/xmtp-android/pull/101/files)
> Read Receipt Content Type

- lib/src/client.dart
- lib/src/common/topic.dart
- lib/src/conversation/conversation.dart
- lib/src/conversation/conversation_v1.dart
- lib/src/conversation/conversation_v2.dart
- lib/src/conversation/manager.dart
- test/client_test.dart
- test/common/topic_test.dart
ref
https://github.com/xmtp/xmtp-ios/pull/87
https://github.com/xmtp/xmtp-android/pull/105
> feat: add support for ephemeral messages

- README.md
Add deprecation notice. Related [PR](https://github.com/xmtp/xmtp-dot-org/pull/710) in docs
> Depreciation Notice
